# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: v1
generate:
  models: true
output: ../backends/pkg/reconciler/eventmesh/v1/api.gen.go
