// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve EventMesh
	// (GET /getEventMesh)
	GetEventMesh(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEventMesh operation middleware
func (siw *ServerInterfaceWrapper) GetEventMesh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventMesh(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/getEventMesh", wrapper.GetEventMesh).Methods("GET")

	return r
}

type GetEventMeshRequestObject struct {
}

type GetEventMeshResponseObject interface {
	VisitGetEventMeshResponse(w http.ResponseWriter) error
}

type GetEventMesh200JSONResponse EventMesh

func (response GetEventMesh200JSONResponse) VisitGetEventMeshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEventMesh401JSONResponse struct {
	Error string `json:"error"`
}

func (response GetEventMesh401JSONResponse) VisitGetEventMeshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Retrieve EventMesh
	// (GET /getEventMesh)
	GetEventMesh(ctx context.Context, request GetEventMeshRequestObject) (GetEventMeshResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEventMesh operation middleware
func (sh *strictHandler) GetEventMesh(w http.ResponseWriter, r *http.Request) {
	var request GetEventMeshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventMesh(ctx, request.(GetEventMeshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventMesh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventMeshResponseObject); ok {
		if err := validResponse.VisitGetEventMeshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra227bOBN+FYL/D/RGdpy2e/Jd0u4WQdtF0QP2og4QWhpbrCWSS1Ju3cDvvhiStiRL",
	"smU3bdKrWDzMfHMekrmlscyVFCCsoeNbauIUcuZ+Xmq5AI2/EjCx5spyKeg4jBNuCCOG5yrjMw4J0aA0",
	"GBCW4ToiZ4SRl4JZvgTy5xKE5WJOwl6bMosEgBmOn5LEUpgiBzJdEZsCuWTxwlg2B6KyYs7FkEZUaalA",
	"Ww4OHRNCelb+M0k4frDsTW3ZTOqcWTqmxmou5jSidqWg/F5HO9JdlHRRBgQzdaARAnxhucoACS9gRcd0",
	"ybICkEigKqefILY4kLEpZHcL7ZUj+U2oBMuhadG/WQ57yNJ8NfDDNOqDGpkYxeIOTm7qALuSRC+OSssl",
	"TyBxfvZ+pbyCd7THjUWugGsIkjBks2/jdi1oPtbgnOWrgSMwcBiuI8ot5H3NGQaY1myF3wVPmjg/XD3f",
	"p5zzx0+eDn759bffB3+Mzh/3UE9EvwzmcuAtj9Tpeh1RDf8WXEOCAlaV7ZZ5ZFsfjmrB1qrt6xZfc9Ov",
	"waRNGbdTmARQUivVIIMlZMRYXcTWZ4hUZomf90bLcUfCLBuSK/vIz1TWPzLEgOYs418hIUwkxDhTy54p",
	"xavbdGU841NeFvyIZVkwkCFcOBZxVhjrDbZ1i/9rmNEx/d9ZmWfPQpI9Cxm2xTNgjyOXam8Cqjr3Dijy",
	"T8ozIJ+BxEwQyKeQVFRb2xLEinDxAkDhYE4MKKaZBTKFmBUGiJAWd+tVhYYzKJYDKwmrOHAvfWwla1OJ",
	"kYWO2/Txzk80lWE2E6dZx9NthVJMEcCUTbNWQNXpFlj16RPBVYg0Ie4EeMWboq2X74pRargzmJ1puv3x",
	"tJag3P5zdQWlzw/J+xQMEKaBKGYMJh+0e0TgSwwqJDOcnfHMgoaEyMJuhLr5yw1WONyQWSFi/HlkdQ/q",
	"Si5XTSs92855M91MitHoSVxWNvzlxuBm667OM/1G3Sb4/kK52fmtZbImyK5cz8uvAwDp+xSdq5aqIOfW",
	"QkI+pyCIkTnYFH0yZUqBMMN+3cd3b/UOu9qdt4FdOqz3P3feDu5he2RLqGEGGoTnui+TvtCyUC+5SLZg",
	"3C+X592S58wyD11piJnFnGp1Abs2e+dW+/6kBv524uBN6HgSbDCh0aSSuSZ0fDuhMw5Zcu5/b9d7gSZ0",
	"vV73k9tj/vD2VUtn+fbVphnyq+owU2uVGZ9h5IbpWOZVpoXOusN1l5nL6FWr1pltY23gYw2SfuIdapm7",
	"HOjotrlHkxxCYG+vXEnJbWW1y/kaInYsDCW3tWee45aILLhIIrKFH7nGWIRQZ+RlMQUtwIIhGnwH0Cyr",
	"jlQTVGXvxZsrz3BjiA2xiHzmNsV6h6NL0Ga3rvn2hIv5cOF7g2ECy37egLIdhIWLdlHVAVweebjdnzrb",
	"eXzHM3Qnw6NS5o6/e5MHFUdN92/z5tAxd3Top7WHYe/P1Ru22ONwUT4hyHqHWGjtf0CEtbniheLvQC9B",
	"Bwd5GF3VSUY6HP4dsWiOEP2Y4L+L0G+50jlwiVY5tLVepAVUlW7VxX048RgF8RA33mykKO809p0psGm4",
	"w+u3Y24NK5cuh2V1Qu47X92n1IaLxTf0xIcasDZ/fJh3llG9xrUWtOoty957nhOLW5XC8SUuuFz9Qilm",
	"gkyBxCkTArMd82Uhl3lowu+vKlZw/oDaWOHWo0LmYAyb/5gutFMR9Eq8hlzq1TNvvYdSKU83XI962akM",
	"rJrVALz72rmP9T09QXVius+HqG5FPYDUvnNS6fU6hXUQ4kJzu3LXNuEBCJgGfVHYdPsUjpv8cClJaq2i",
	"a6TBxUw2FYfhbiXRYDWHJZSl3r94Ca+ikIEst06R5YKLN1c0oiFJoYqHo+EIrSQVCKY4HdMnw9HwHGVl",
	"NnXIz+Zga+9tc7BNYG/BFlqYHUBeJ1hsLOMCy9LmWYuJpOqrCBezisN+ldAxfVHlilY0Sgrjlfl4NMI/",
	"SBaEA8OUynjsdp99Mv4y13ccvR6GHBOn9t0yHMdgzKzIstVW6UmrkENU49PR+VHA6vUStJbunyLKGPgg",
	"WGFTqflXd4u1/1zt97d4ZEOuKtlhzWXp+GPdWT9er68jaoo8Z3rlDe1dr6a49X8BAAD//1inohztIQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
