// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve EventMesh
	// (GET /getEventMesh)
	GetEventMesh(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEventMesh operation middleware
func (siw *ServerInterfaceWrapper) GetEventMesh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventMesh(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/getEventMesh", wrapper.GetEventMesh).Methods("GET")

	return r
}

type GetEventMeshRequestObject struct {
}

type GetEventMeshResponseObject interface {
	VisitGetEventMeshResponse(w http.ResponseWriter) error
}

type GetEventMesh200JSONResponse EventMesh

func (response GetEventMesh200JSONResponse) VisitGetEventMeshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEventMesh401JSONResponse struct {
	Error string `json:"error"`
}

func (response GetEventMesh401JSONResponse) VisitGetEventMeshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Retrieve EventMesh
	// (GET /getEventMesh)
	GetEventMesh(ctx context.Context, request GetEventMeshRequestObject) (GetEventMeshResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEventMesh operation middleware
func (sh *strictHandler) GetEventMesh(w http.ResponseWriter, r *http.Request) {
	var request GetEventMeshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEventMesh(ctx, request.(GetEventMeshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEventMesh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventMeshResponseObject); ok {
		if err := validResponse.VisitGetEventMeshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZWW/bOBD+KwR3gb7IR9ru5be03V0EbRdFD+xDHCC0NLZYSySXpNyqgf/7YkhZlyVH",
	"dtMmfYrFY+abg98MmRsaylRJAcIaOruhJowhZe7nMy3XoPFXBCbUXFkuBZ0V44QbwojhqUr4kkNENCgN",
	"BoRluI7IJWHkpWCWb4D8uQFhuViRYq+NmUUBwAzHT0lCKUyWAlnkxMZAnrFwbSxbAVFJtuJiTAOqtFSg",
	"LQeHjgkhvSr/GUUcP1jyprFsKXXKLJ1RYzUXKxpQmyuovrdBy7rzSi7agGAWDjRCgM8sVQmg4DXkdEY3",
	"LMkAhRRS5eIjhBYHEraA5G6hvXIivwqVYCnsR/QflsIBsTTNR36YBkNQoxKjWNijyU3doq4SMUij0nLD",
	"I4hcnr3PlXdwy3vcWNQKuIagCEN2+3Zp14HmsgFnkuYjJ2DkMFwFlFtIh4azGGBasxy/Mx7t4/xw8eKQ",
	"c84eP3k6+uXX334f/TE9ezzAPQH9PFrJkY88SqfbbUA1/JdxDREaWHe2W+aRlTkcNA5bp7evOnLNTb8G",
	"E+/bWE4hCaClVqpRAhtIiLE6C61niFgmkZ/3QUtxR8QsG5ML+8jP1NY/MsSA5izhXyAiTETEuFDLgZTi",
	"3W36GM94ykuKPGJJUgTIEC6cijDJjPUBK9PiZw1LOqM/TSqenRQkOykYtiMz4EAiV27fB1RP7hYo8m/M",
	"EyCfgIRMEEgXENVc29hSmBXg4jWAwsGUGFBMMwtkASHLDBAhLe7WeU2GCyiWAysJqyXwIH+UlnW5xMhM",
	"h13+eOcn9p1hdhOnRcfL7YSSLRDAgi2STkD16Q5YzekTwdWE7ENsHfBaNgVllrfNqDzce5hdaPrz8bSW",
	"oNr+Y3UFVc6PyfsYDBCmgShmDJIPxj0g8DkEVZAZzi55YkFDRGRmd0Zd/+UGaxquyTITIf48sroX7oqe",
	"5ftRel7O+TBdz7Pp9ElYVTb85cbgukxXl5l+o+4y/HCh3O382jLZMKRt14vq6xaA9H2MydWgKki5tRCR",
	"TzEIYmQKNsacjJlSIMx4WPfxzVu921PtztvAPh82+587bwcPqD2yJdSwBA2iS+vb3dSu+6gq6iNDyo2+",
	"hGnwtEgSvoaypBGpCSNhzISABLsRFFVQuQdHrldaZmqy5iKaNE/ZddM2KJhwvPbUOI5gM/FqJu0jdUwb",
	"7kvFC2aZd4HSEDKLFcHqDNoZ986t9t1VA97N3Ime09m8yKA5DeY13p3T2c2cLjkk0Zn/Xa73YOZ0u90e",
	"g/nD21cdffHbV7tWzq9qwoytVWY2QScV06FM60oznfSTTVuZq0f1nGwqK5li5JkComHm3dbw96X/0U3/",
	"gBa/OMAHO/1aQelqCooOqacjO60dKPb+WL2Ap4gjSdjxw77zXmYL0AIsGHL+5oK4VU09AfnEbYwtBI5t",
	"QJt2q7Br5eqUMixDka5uxYSLDphOzxV/B3oDukiQh1FFTwrS7ZWyywFIQkeYfkyF7FH3DR9Mag1656NJ",
	"B6JLx5Df8aWkyysP86Vkd+6Lo9ZJq/W73cHb5YkUW5dwPNEWLWjzGhsyQRaw64gMYZ6cUpkWxfP+uLmG",
	"8zswdE3bAJ5OwRi2ajV/34qp+xxBL8RrSKXOn/voPRS+Pj1wA1i71xnI3fUDePcMfkj1PT1892K6z+fv",
	"fkc9AGpvsPjAN3G84ECYaW5zd90qnp2BadDnmY3Lf8DhJj9cWYIXHLxIBZSLpdx3HB53K4kGqzlsoLrY",
	"+nd24V1UMJDl1jmyWnD+5oIGtCApdPF4Op5ilKQCwRSnM/pkPB2foa3Mxg75ZAW28cq/Att13baZFqYF",
	"yPsEi41lXGBZ2j2mMxHVcxXhIqs47BcRndG/61oxikZJYbwzH0+n+AfFgnBgmFIJD93uyUfjn5D8DXHQ",
	"c7RT4tzeLsNhCMYssyTJS6dHnUaO0Y1Pp2dHAWvWS9Baun/FVmfgg2CZjaXmX9zt8/D9z+/vyMg9u+pi",
	"x42UpbPLZrJeXm2vAmqyNGU694H2qddw3Pb/AAAA//+CuZeBYx4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
