name: Backstage lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'backstage/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'backstage/yarn.lock'

      - name: Print environment
        run: |
          node --version
          yarn --version

      - name: Install dependencies
        shell: bash
        working-directory: ./backstage
        run: yarn --prefer-offline --frozen-lockfile

      - name: Lint all code
        shell: bash
        working-directory: ./backstage
        run: yarn backstage-cli repo lint